#!/bin/bash

set +e

IMAGE=nmrpflash
CONTAINER=${IMAGE}-container
REPO_ROOT="$(readlink -f $(dirname $(dirname $0)))"

dexec() {
	docker exec $CONTAINER $@
}

cd "$REPO_ROOT"

docker build -t $IMAGE .

if [ $1 != "reuse" ]; then
	docker stop $CONTAINER
	docker rm $CONTAINER
	docker run -t -d --name $CONTAINER $IMAGE
	dexec git clone https://github.com/jclehner/nmrpflash .
	dexec git checkout remotes/origin/gui
fi

dexec ./scripts/build-and-package linux
dexec ./scripts/build-and-package win32 cross

dexec find ./out -type f -print0 | while read -r -d '' f; do
	echo "$f"
	docker cp $CONTAINER:"$f" out/
done
